# Documentation about Garden projects can be found at https://docs.garden.io/using-garden/projects
# Reference for Garden projects can be found at https://docs.garden.io/reference/project-config
apiVersion: garden.io/v1
kind: Project
name: demo-gimlet
dotIgnoreFile: .gitignore
defaultEnvironment: local

environments:
  - name: local
    defaultNamespace: default

varfile: .env

providers:
  - name: local-kubernetes
    environments: [local]
    setupIngressController: null
