apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gimlet

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/gimlet-io/gimlet/main/deploy/gimlet.yaml
  - ingress.yaml

patches:
  - path: configmap.patch.yaml
  - path: ingress.patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: gimlet
